### ISSUE TITLE
is remote interpreter down ?

### ISSUE THREAD

**Issue by musisician** [Zilliqa/kaya#70]
hi i want to test kaya rpc deploy contract, im user windows, so im used remote interpreter scilla, but its always throwing an error,
this my log

[Logic.js]       : Processing transaction...
[Logic.js]       : Payload well-formed? true
[Logic.js]       : Sender: b9998710c6c5b7ad49bda5080031412c5a3f20d3
[Wallet]         : Getting balance for b9998710c6c5b7ad49bda5080031412c5a3f20d3
[Logic.js]       : User Nonce: 0
[Logic.js]       : Payload Nonce: 1
[Logic.js]       : Task: Contract Deployment / Create Transaction
[Wallet]         : Getting balance for b9998710c6c5b7ad49bda5080031412c5a3f20d3
[Wallet]         : Checking if b9998710c6c5b7ad49bda5080031412c5a3f20d3 has 25002000200000000
[Wallet]         : Funds sufficient true
[Logic.js]       : Running scilla interpreter now
[Wallet]         : Increasing nonce for b9998710c6c5b7ad49bda5080031412c5a3f20d3
[Wallet]         : New nonce for b9998710c6c5b7ad49bda5080031412c5a3f20d3 : 1
[Scilla]         : blockchain.json file prepared for blocknumber: 68
[Scilla]         : Code Deployment
[Scilla]         : Running Remote Interpreter
throwing interpreter error

can i get explained about this ?

**Comment by edisonljh** [comment]
Yes remote interpreter is down. The current RPC only works with local interpreter.
We are patching it and we will announce it once it's up.
